apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis-container
    #image: kubernetes/redis:v1
    image: redis:v1
    volumeMounts:
    - mountPath: /redis-master
      name: configmap
  volumes:
  - name: configmap
    configMap:
      name: example-redis-config
      items:
      - key: redis-config
        path: redis.conf
