apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-using-literals-environment-variables
spec:
  containers:
  - name: accessing-from-literal-config-maps-using-env
    image: k8s.gcr.io/busybox
    command: ["/bin/sh","-c","env"]
    env:
    - name: SPECIAL_KEY
      valueFrom:
        configMapKeyRef:
          name: special-configmap
          key: name
  restartPolicy: Never
