apiVersion: v1
kind: Pod
metadata:
   name: volume-hostpath
spec:
  containers:
  - name: hostpath-container
    image: redis
    volumeMounts:
    - name: hostpath
      mountPath: /test-mnt
  volumes:
  - name: hostpath
    hostPath: 
      path: /test-vol1
