apiVersion: apps/v1
kind: DaemonSet
metadata: 
   name: fluentd-ds
spec:
   template:
     metadata:
       name: fluentd-ds-pod
       labels:
         app: fluentd
     spec:
       containers:
       - name: fluentd-container
         image: gcr.io/google-containers/fluentd-elasticsearch:1.20
   selector:
     matchLabels:
       app: fluentd
