apiVersion: v1
kind: Pod
metadata:
  name: secrets-using-volumes
spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
    - name: mounting-secrets
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: mounting-secrets 
    secret:
      secretName: my-secret
